# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af616944ac69d47601403e7a14efe6447ca1f8ba030c6affd539836b14846506adc57fd7b23253d42fc7357257ccb0fc85185f2002714fc2560c88b0faa3465e


test:
  secret_key_base: 29719008149b358a365279916c95ef7ca14a15c0c98e0aa199c870b91f9914068a9e917eb133ba57f49f65110705f08a79d9a951bbcc64ce37ca334eb36c3d31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  vkontakte_app_secret: <%= ENV["VKONTAKTE_APP_SECRET"] %>
  mail_password_secret: <%= ENV["MAIL_PASSWORD_SECRET"] %>
